version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      echo Build Starting on `date`
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/BarberiaVIP-0.0.1-SNAPSHOT.jar
  discard-paths: yes

